[project]
name = "fintech-deal-management-ui"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "faker>=40.1.0",
    "reflex>=0.8.24.post1",
    "sqlmodel>=0.0.31",
]
